const assert=require('assert');
const{normalize,fromEvents}=require('./persistence/appointments');
const{applyAppointmentOutcome,applyVisitOutcome}=require('./commercial-workflow');
const a=normalize({clientName:'Ana',phone:'(51) 99999-0000',date:'2026-08-29',time:'14:30',type:'visita',leadId:'lead-1'});
assert.equal(a.phone,'51999990000');
assert.equal(a.type,'VISITA');
assert.equal(a.leadId,'lead-1');
const events=[{type:'APPOINTMENT_UPSERT',payload:{appointment:a}},{type:'APPOINTMENT_UPSERT',payload:{appointment:{...a,status:'CONFIRMED'}}}];
assert.equal(fromEvents(events).length,1);
assert.equal(fromEvents(events)[0].status,'CONFIRMED');
const confirmed=applyAppointmentOutcome({status:'AGUARDANDO_CONFIRMACAO_AGENDA'},{confirmed:true,mode:'PRESENCIAL'});
assert.equal(confirmed.lead.status,'CONFIRMED');
assert.equal(confirmed.nextAction,'REALIZAR_ATENDIMENTO');
const converted=applyVisitOutcome({status:'CONFIRMED'},'CONVERTIDO');
assert.equal(converted.lead.stage,'CONVERTIDO');
assert.equal(converted.lead.status,'CONFIRMED','status do robô não muda com resultado de visita — só o stage comercial');
assert.equal(converted.nextAction,'REGISTRAR_CONVERSAO');
console.log('PASS appointments domain + lead workflow sync');
