const assert=require('assert');
const{normalize,fromEvents}=require('./persistence/appointments');
const{applyAppointmentOutcome}=require('./commercial-workflow');
const a=normalize({clientName:'Ana',phone:'(51) 99999-0000',date:'2026-08-29',time:'14:30',type:'visita'});
assert.equal(a.phone,'51999990000');
assert.equal(a.type,'VISITA');
const events=[{type:'APPOINTMENT_UPSERT',payload:{appointment:a}},{type:'APPOINTMENT_UPSERT',payload:{appointment:{...a,status:'CONFIRMED'}}}];
assert.equal(fromEvents(events).length,1);
assert.equal(fromEvents(events)[0].status,'CONFIRMED');
const lead={status:'AGUARDANDO_CONFIRMACAO_AGENDA'};
const synced=applyAppointmentOutcome(lead,{confirmed:true,mode:'PRESENCIAL'});
assert.equal(synced.lead.status,'CONFIRMED');
assert.equal(synced.nextAction,'REALIZAR_ATENDIMENTO');
console.log('PASS appointments domain + lead workflow sync');
