const assert=require('assert');
const{applyAppointmentOutcome,applyVisitOutcome,summarizeWorkflow}=require('./commercial-workflow');
let r=applyAppointmentOutcome({status:'AGUARDANDO_CONFIRMACAO_AGENDA'},{confirmed:false,mode:'PRESENCIAL'});
assert.equal(r.lead.status,'SCHEDULING');
assert.equal(r.lead.stage,'SCHEDULING');
assert.equal(r.nextAction,'AGUARDAR_CONFIRMACAO');
r=applyAppointmentOutcome({status:'AGUARDANDO_CONFIRMACAO_AGENDA'},{confirmed:true,mode:'PRESENCIAL'});
assert.equal(r.lead.status,'CONFIRMED');
assert.equal(r.lead.stage,'CONFIRMED');
assert.equal(r.nextAction,'REALIZAR_ATENDIMENTO');
r=applyVisitOutcome({status:'CONFIRMED'},'CONVERTIDO');
assert.equal(r.lead.stage,'CONVERTIDO');
assert.equal(r.lead.status,'CONFIRMED','status do robô não deve mudar com resultado de visita');
assert.equal(r.nextAction,'REGISTRAR_CONVERSAO');
r=applyVisitOutcome({status:'CONFIRMED'},'AGUARDANDO_RETORNO');
assert.equal(r.lead.stage,'AGUARDANDO_RETORNO');
assert.equal(r.lead.status,'CONFIRMED','status do robô não deve mudar com resultado de visita');
assert.equal(r.nextAction,'FAZER_FOLLOW_UP');
r=applyVisitOutcome({status:'CONFIRMED',stage:'CONFIRMED'},'ALGO_DESCONHECIDO');
assert.equal(r.changed,false);
assert.equal(r.lead.status,'CONFIRMED');
assert.equal(r.lead.stage,'CONFIRMED');
assert.equal(summarizeWorkflow({status:'CONFIRMED'}).status,'CONFIRMED');
assert.equal(summarizeWorkflow({status:'CONFIRMED'}).stage,'CONFIRMED');
assert.equal(summarizeWorkflow({status:'CONFIRMED',stage:'NEGOTIATION'}).stage,'NEGOTIATION');
console.log('PASS commercial workflow');
