const assert=require('assert');
const{applyAppointmentOutcome,applyVisitOutcome,summarizeWorkflow}=require('./commercial-workflow');
let r=applyAppointmentOutcome({status:'AGUARDANDO_CONFIRMACAO_AGENDA'},{confirmed:false,mode:'PRESENCIAL'});
assert.equal(r.lead.status,'AGUARDANDO_CONFIRMACAO_AGENDA');
assert.equal(r.nextAction,'AGUARDAR_CONFIRMACAO');
r=applyAppointmentOutcome({status:'AGUARDANDO_CONFIRMACAO_AGENDA'},{confirmed:true,mode:'PRESENCIAL'});
assert.equal(r.lead.status,'CONFIRMED');
assert.equal(r.nextAction,'REALIZAR_ATENDIMENTO');
r=applyVisitOutcome({status:'CONFIRMED'},'CONVERTIDO');
assert.equal(r.lead.status,'CONVERTIDO');
assert.equal(r.nextAction,'REGISTRAR_CONVERSAO');
r=applyVisitOutcome({status:'CONFIRMED'},'AGUARDANDO_RETORNO');
assert.equal(r.lead.status,'AGUARDANDO_RETORNO');
assert.equal(r.nextAction,'FAZER_FOLLOW_UP');
assert.equal(summarizeWorkflow({status:'CONFIRMED'}).status,'CONFIRMED');
console.log('PASS commercial workflow');
