const { toDbLead, fromDbLead } = require('./crm-mapper');
const input = { companyName:'Empresa Teste', name:'Ana', phone:'5551999999999', interest:'CONTA_PJ', updatedAt:'2026-08-22T12:00:00Z', status:'NEW', address:'Rua Teste', city:'Canoas', state:'RS', zipCode:'92000000' };
const db = toDbLead(input);
if (db.nome_da_empresa !== 'Empresa Teste' || db.nome !== 'Ana' || db.telefone !== input.phone || db.interesse_no_produto !== input.interest) throw Error('CRM_TO_DB_MAPPING_FAILED');
if (db.atualizado_em !== input.updatedAt || db.status !== input.status) throw Error('CRM_METADATA_TO_DB_MAPPING_FAILED');
if (db.address !== input.address || db.city !== input.city || db.state !== input.state || db.zip_code !== input.zipCode) throw Error('CRM_LOCATION_TO_DB_MAPPING_FAILED');
const crm = fromDbLead(db);
if (crm.companyName !== input.companyName || crm.name !== input.name || crm.phone !== input.phone || crm.interest !== input.interest) throw Error('DB_TO_CRM_MAPPING_FAILED');
if (crm.updatedAt !== input.updatedAt || crm.status !== input.status) throw Error('DB_TO_CRM_METADATA_MAPPING_FAILED');
if (crm.address !== input.address || crm.city !== input.city || crm.state !== input.state || crm.zipCode !== input.zipCode) throw Error('DB_TO_CRM_LOCATION_MAPPING_FAILED');
console.log('PASS CRM/Supabase mapper round-trip with current V1 schema');
