/** Server-side Supabase adapter. The existing V1 production schema remains the source of truth. */
const { TABLES, assertRepository } = require('./supabase-contract');
const { toDbLead, fromDbLead } = require('./crm-mapper');
function cleanRow(row={}){const out={};for(const [k,v] of Object.entries(row)){if(v===undefined||v===null)continue;if(typeof v==='string'&&v.trim()==='')continue;out[k]=v}return out}
function normalizePhone(value){const v=String(value||'').replace(/\D/g,'');return v||null}
function normalizeJid(value){const v=String(value||'').trim().toLowerCase();return v&&v.includes('@')?v:null}
function baseLeadRow(row){const allowed=['name','company_name','phone','whatsapp_jid','cnpj','source','campaign','product_interest','bank_current','machine_current','monthly_revenue','pain_point','status','stage','owner','next_action','address','city','state','zip_code'];const out={};for(const k of allowed)if(row[k]!==undefined)out[k]=row[k];return cleanRow(out)}
function optionalLeadRow(row){const allowed=['updated_at','company_status','trade_name','neighborhood','address_number'];const out={};for(const k of allowed)if(row[k]!==undefined)out[k]=row[k];return cleanRow(out)}
const ATOMIC_RECHECK_MS=5*60*1000;
function atomicEnabled(env=process.env){return!['off','false','0'].includes(String(env.CRM_ATOMIC_INBOUND||'').trim().toLowerCase())}
function isMissingFunctionError(error){const code=String(error?.code||'');return code==='PGRST202'||code==='42883'||/could not find the function|function .*crm_ingest_whatsapp_inbound.* does not exist/i.test(String(error?.message||''))}
function atomicUnavailable(){const e=new Error('ATOMIC_INGEST_UNAVAILABLE');e.code='ATOMIC_INGEST_UNAVAILABLE';return e}
function createSupabaseRepository(client) {
  if (!client || typeof client.from !== 'function') throw new Error('SUPABASE_CLIENT_REQUIRED');
  let atomicUnavailableUntil=0;
  const repo={
    async listLeads({limit=50,source,status,stage}={}){let q=client.from(TABLES.leads).select('*').order('updated_at',{ascending:false}).order('created_at',{ascending:false}).limit(limit);if(source)q=q.eq('source',source);if(status)q=q.eq('status',status);if(stage)q=q.eq('stage',stage);const{data,error}=await q;if(error)throw error;return(data||[]).map(fromDbLead)},
    async getLead(id){const{data,error}=await client.from(TABLES.leads).select('*').eq('id',id).single();if(error&&error.code!=='PGRST116')throw error;return data?fromDbLead(data):null},
    async findOrCreateLeadByWhatsappIdentity({phone,jid}={},defaults={}){
      const normalizedPhone=normalizePhone(phone), normalizedJid=normalizeJid(jid);
      if(!normalizedPhone&&!normalizedJid)throw new Error('WHATSAPP_IDENTITY_REQUIRED');
      let existing=null;
      if(normalizedPhone){const r=await client.from(TABLES.leads).select('*').eq('phone',normalizedPhone).limit(1);if(r.error)throw r.error;if(r.data?.[0])existing=r.data[0]}
      if(!existing&&normalizedJid){const r=await client.from(TABLES.leads).select('*').eq('whatsapp_jid',normalizedJid).limit(1);if(r.error)throw r.error;if(r.data?.[0])existing=r.data[0]}
      if(existing){const patch={};if(normalizedPhone&&!existing.phone)patch.phone=normalizedPhone;if(normalizedJid&&!existing.whatsapp_jid)patch.whatsappJid=normalizedJid;if(defaults.name&&!existing.name)patch.name=defaults.name;if(Object.keys(patch).length)return this.updateLead(existing.id,patch);return fromDbLead(existing)}
      return this.createLead({phone:normalizedPhone,whatsappJid:normalizedJid,source:defaults.source||'WHATSAPP',name:defaults.name||null})
    },
    async findOrCreateLeadByPhone(phone,defaults={}){const normalized=normalizePhone(phone);if(!normalized)throw new Error('PHONE_REQUIRED');return this.findOrCreateLeadByWhatsappIdentity({phone:normalized},defaults)},
    async ingestInboundMessage(message={}){
      // RPC atômica é opcional: se a migration 20260923 ainda não foi aplicada (PGRST202/42883)
      // ou se CRM_ATOMIC_INBOUND=off, sinaliza ATOMIC_INGEST_UNAVAILABLE e o pipeline usa o caminho legado.
      if(!atomicEnabled()||typeof client.rpc!=='function'||Date.now()<atomicUnavailableUntil)throw atomicUnavailable();
      const externalId=String(message.external_message_id||'').trim();
      if(!externalId)throw new Error('EXTERNAL_MESSAGE_ID_REQUIRED');
      const args={p_phone:normalizePhone(message.phone),p_whatsapp_jid:normalizeJid(message.whatsapp_jid),p_name:message.name||null,p_source:message.source||'WHATSAPP',p_external_message_id:externalId,p_text_content:message.text||'',p_message_timestamp:message.timestamp||null,p_metadata:{type:message.type||'text',media_url:message.media_url||null,source:message.source||'WHATSAPP',campaign:message.campaign||null,timestamp:message.timestamp||null,whatsapp_jid:normalizeJid(message.whatsapp_jid)}};
      const{data,error}=await client.rpc('crm_ingest_whatsapp_inbound',args);if(error){if(isMissingFunctionError(error)){atomicUnavailableUntil=Date.now()+ATOMIC_RECHECK_MS;console.warn('SUPABASE_ATOMIC_INGEST_UNAVAILABLE',{code:error.code||null,recheckInMs:ATOMIC_RECHECK_MS});throw atomicUnavailable()}throw error}
      const result=Array.isArray(data)?data[0]:data;if(!result?.lead||!result?.message)throw new Error('SUPABASE_ATOMIC_INGEST_INVALID_RESULT');
      return{lead:fromDbLead(result.lead),saved:result.message,event:result.event||null,duplicate:Boolean(result.duplicate)};
    },
    async createLead(payload){const row=cleanRow(toDbLead(payload));const full=await client.from(TABLES.leads).insert(row).select('*').single();if(!full.error)return fromDbLead(full.data);if(full.error.code==='23505'){const phone=normalizePhone(row.phone);const jid=normalizeJid(row.whatsapp_jid);const cnpj=row.cnpj?String(row.cnpj).replace(/\D/g,''):'';let existing=null;if(phone){const r=await client.from(TABLES.leads).select('*').eq('phone',phone).limit(1);if(!r.error&&r.data?.[0])existing=r.data[0]}if(!existing&&jid){const r=await client.from(TABLES.leads).select('*').eq('whatsapp_jid',jid).limit(1);if(!r.error&&r.data?.[0])existing=r.data[0]}if(!existing&&cnpj){const r=await client.from(TABLES.leads).select('*').eq('cnpj',cnpj).limit(1);if(!r.error&&r.data?.[0])existing=r.data[0]}if(existing)return fromDbLead(existing)}const base=baseLeadRow(row);const retry=await client.from(TABLES.leads).insert(base).select('*').single();if(!retry.error){const optional=optionalLeadRow(row);if(Object.keys(optional).length){try{const updated=await client.from(TABLES.leads).update(optional).eq('id',retry.data.id).select('*').single();if(!updated.error)return fromDbLead(updated.data)}catch{}}return fromDbLead(retry.data)}if(retry.error?.code==='23505'){const phone=normalizePhone(base.phone);const jid=normalizeJid(base.whatsapp_jid);const cnpj=base.cnpj?String(base.cnpj).replace(/\D/g,''):'';let existing=null;if(phone){const r=await client.from(TABLES.leads).select('*').eq('phone',phone).limit(1);if(!r.error&&r.data?.[0])existing=r.data[0]}if(!existing&&jid){const r=await client.from(TABLES.leads).select('*').eq('whatsapp_jid',jid).limit(1);if(!r.error&&r.data?.[0])existing=r.data[0]}if(!existing&&cnpj){const r=await client.from(TABLES.leads).select('*').eq('cnpj',cnpj).limit(1);if(!r.error&&r.data?.[0])existing=r.data[0]}if(existing)return fromDbLead(existing)}throw retry.error||full.error},
    async createCapturedCompany(payload){const allowed=['name','phone','cnpj','address','city','state','segment','whatsapp','email','source','raw_data','status','lead_id','activated_at','created_at','updated_at'];const row={};for(const k of allowed)if(payload?.[k]!==undefined)row[k]=payload[k];const{data,error}=await client.from(TABLES.capturedCompanies).insert(cleanRow(row)).select('*').single();if(error)throw error;return data},
    async listCapturedCompanies({limit=100,status,source}={}){let q=client.from(TABLES.capturedCompanies).select('*').order('created_at',{ascending:false}).limit(limit);if(status)q=q.eq('status',status);if(source)q=q.eq('source',source);const{data,error}=await q;if(error)throw error;return data||[]},
    async findDuplicateCompany({phone,cnpj,name,address}={}){if(cnpj){const{data,error}=await client.from(TABLES.capturedCompanies).select('*').eq('cnpj',String(cnpj).replace(/\D/g,'')).limit(1);if(error)throw error;if(data?.[0])return data[0]}if(phone){const{data,error}=await client.from(TABLES.capturedCompanies).select('*').eq('phone',String(phone).replace(/\D/g,'')).limit(1);if(error)throw error;if(data?.[0])return data[0]}if(name&&address){const{data,error}=await client.from(TABLES.capturedCompanies).select('*').eq('name',name).eq('address',address).limit(1);if(error)throw error;if(data?.[0])return data[0]}return null},
    async getCapturedCompany(id){const{data,error}=await client.from(TABLES.capturedCompanies).select('*').eq('id',id).single();if(error&&error.code!=='PGRST116')throw error;return data||null},
    async updateCapturedCompany(id,patch){const allowed=['name','phone','cnpj','address','city','state','segment','whatsapp','email','source','raw_data','status','lead_id','activated_at','created_at','updated_at'];const row={};for(const k of allowed)if(patch?.[k]!==undefined)row[k]=patch[k];const{data,error}=await client.from(TABLES.capturedCompanies).update(cleanRow(row)).eq('id',id).select('*').single();if(error)throw error;return data},
    async updateLead(id,patch){const{data,error}=await client.from(TABLES.leads).update(cleanRow(toDbLead(patch))).eq('id',id).select('*').single();if(error)throw error;return fromDbLead(data)},
    async createMessage(payload){const row={lead_id:payload.lead_id,channel:payload.channel||'WHATSAPP',direction:payload.direction||'INBOUND',external_message_id:payload.external_message_id||null,text_content:payload.text_content!==undefined?payload.text_content:(payload.text||''),transcript:payload.transcript||null,metadata:payload.metadata||{}};const{data,error}=await client.from(TABLES.messages).insert(row).select('*').single();if(error)throw error;return data},
    async listMessages({leadId,limit=100}={}){const{data,error}=await client.from(TABLES.messages).select('*').eq('lead_id',leadId).order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data||[]},
    async createEvent(payload){const row={lead_id:payload.lead_id||null,type:payload.type||payload.event_type||'SYSTEM',idempotency_key:payload.idempotency_key||null,payload:payload.payload||payload.metadata||{}};if(row.idempotency_key){const{data:existing,error:findError}=await client.from(TABLES.events).select('*').eq('idempotency_key',row.idempotency_key).limit(1);if(findError)throw findError;if(existing&&existing[0])return existing[0]}const{data,error}=await client.from(TABLES.events).insert(row).select('*').single();if(error)throw error;return data},
    async listEvents({leadId,type,limit=100}={}){let q=client.from(TABLES.events).select('*').order('created_at',{ascending:false}).limit(limit);if(leadId)q=q.eq('lead_id',leadId);if(type)q=q.eq('type',type);const{data,error}=await q;if(error)throw error;return data||[]},
    async createAudit(payload){const row={lead_id:payload.lead_id||null,action:payload.action||payload.event_type||'SYSTEM',from_status:payload.from_status||null,to_status:payload.to_status||null,from_stage:payload.from_stage||null,to_stage:payload.to_stage||null,actor:payload.actor||'SYSTEM',metadata:payload.metadata||payload.payload||{}};const{data,error}=await client.from(TABLES.audit).insert(row).select('*').single();if(error)throw error;return data}
  };
  return assertRepository(repo);
}
module.exports={createSupabaseRepository};
