const assert=require('assert');const {jidToPhone,extractInboundPhone,slotId,isSessionStale,STALE_SESSION_TIMEOUT_MS,backoffDelay,MAX_AUTO_RECONNECT_ATTEMPTS}=require('./qr-manager');
assert.strictEqual(slotId(1),1);assert.strictEqual(slotId('4'),4);assert.throws(()=>slotId(0),/INVALID_SLOT/);assert.throws(()=>slotId(5),/INVALID_SLOT/);
assert.strictEqual(jidToPhone('5511999999999@s.whatsapp.net'),'5511999999999');
assert.strictEqual(jidToPhone('123456@lid'),null);
assert.strictEqual(extractInboundPhone({remoteJid:'12345@lid',remoteJidAlt:'5511999999999@s.whatsapp.net'}),'5511999999999');
assert.strictEqual(extractInboundPhone({remoteJid:'5511888888888@s.whatsapp.net'}),'5511888888888');
assert.strictEqual(extractInboundPhone({remoteJid:'12345@lid'}),null);
const now=Date.now();
assert.strictEqual(isSessionStale(null,now),false);
assert.strictEqual(isSessionStale({status:'CONNECTED',startedAt:now-999999},now),false);
assert.strictEqual(isSessionStale({status:'DISCONNECTED',startedAt:now-999999},now),false);
assert.strictEqual(isSessionStale({status:'CONNECTING',startedAt:now-1000},now),false);
assert.strictEqual(isSessionStale({status:'CONNECTING',startedAt:now-(STALE_SESSION_TIMEOUT_MS+1)},now),true);
assert.strictEqual(isSessionStale({status:'QR_READY',startedAt:now-(STALE_SESSION_TIMEOUT_MS+1)},now),true);
assert.strictEqual(isSessionStale({status:'QR_READY',startedAt:now-1},now),false);
assert.strictEqual(backoffDelay(1),5000);
assert.strictEqual(backoffDelay(2),10000);
assert.strictEqual(backoffDelay(3),20000);
assert.strictEqual(backoffDelay(6),60000);
assert.strictEqual(backoffDelay(20),60000);
assert.ok(MAX_AUTO_RECONNECT_ATTEMPTS>=1&&MAX_AUTO_RECONNECT_ATTEMPTS<=10);
console.log('qr-manager tests passed');
