const fs=require('fs'),path=require('path');const {healthResponse}=require('./health');const {verifyMetaSignature}=require('./security/meta-signature');const {createProductionRuntime}=require('./runtime');const {getConfig}=require('./config');const {createQrManager}=require('./qr-manager-factory');const auth=require('./auth');const {buildLeadSummary,scoreLead,priority,rankAppointmentSlots,buildRoutePlan}=require('../backend/commercial-assistant');
const runtime=createProductionRuntime();const qrManager=runtime.repository?createQrManager({repository:runtime.repository}):null;const PUBLIC_DIR=path.join(__dirname,'..','public');
function authorized(headers={}){const value=String(headers.authorization||'');if(value.startsWith('Bearer '))return Boolean(auth.authenticate(value.slice(7)));return false}
function verifyMetaWebhook(query={},env=process.env){const config=getConfig(env),mode=query['hub.mode'],token=query['hub.verify_token'],challenge=query['hub.challenge'];if(mode==='subscribe'&&token&&token===config.metaVerifyToken&&challenge)return{status:200,body:challenge,text:true};return{status:403,body:{error:'META_WEBHOOK_VERIFICATION_FAILED'}}}
function normalizeMetaWebhook(payload={}){const messages=[];for(const entry of(Array.isArray(payload.entry)?payload.entry:[]))for(const change of(entry.changes||[]))for(const message of((change.value||{}).messages||[]))messages.push({channel:'WHATSAPP',external_message_id:message.id||null,phone:message.from||null,timestamp:message.timestamp?new Date(Number(message.timestamp)*1000).toISOString():new Date().toISOString(),type:message.type||'other',text:message.text?.body||'',media_url:null,source:'WHATSAPP',campaign:null});return messages}
async function databaseHealth(){if(!runtime.repository)return{status:503,body:{status:'error',database:'not_configured'}};try{await runtime.repository.listLeads({limit:1});return{status:200,body:{status:'ok',database:'ok'}}}catch(e){return{status:503,body:{status:'error',database:'unavailable'}}}}
function staticFile(name){const safe=path.normalize(name).replace(/^\.\.(?:[\\/]|$)/g,'');const full=path.join(PUBLIC_DIR,safe);if(!full.startsWith(PUBLIC_DIR))return null;try{return{body:fs.readFileSync(full),contentType:name.endsWith('.css')?'text/css; charset=utf-8':name.endsWith('.js')?'application/javascript; charset=utf-8':'text/html; charset=utf-8'}}catch{return null}}
function cleanCnpj(v){return String(v||'').replace(/\D/g,'')}
function first(obj,keys){let found=null;const wanted=keys.map(k=>k.toLowerCase());const walk=x=>{if(found!==null||x==null)return;if(Array.isArray(x)){for(const v of x)walk(v);return}if(typeof x!=='object')return;for(const k of Object.keys(x)){if(wanted.includes(k.toLowerCase())&&x[k]!==null&&x[k]!==''&&typeof x[k]!=='object'){found=x[k];return}}for(const v of Object.values(x))walk(v)};walk(obj);return found}
async function lookupCnpj(cnpj){const value=cleanCnpj(cnpj);if(value.length!==14)throw new Error('CNPJ_INVALIDO');const base=process.env.CNPJ_WS_API_BASE_URL||'https://publica.cnpj.ws/cnpj/';const r=await fetch(`${base.replace(/\/$/,'/')}${value}`,{headers:{Accept:'application/json'}});if(!r.ok){if(r.status===404)throw new Error('CNPJ_NAO_ENCONTRADO');if(r.status===429)throw new Error('CNPJ_RATE_LIMIT');throw new Error(`CNPJ_PROVIDER_${r.status}`)}const d=await r.json();const c=d.estabelecimento||d;const e=c.endereco||{};const address=c.logradouro||e.logradouro||'';const number=c.numero||e.numero||'';const neighborhood=c.bairro||e.bairro||'';const city=c.municipio||c.cidade||e.municipio||e.cidade||'';const state=c.uf||c.estado||e.uf||e.estado||'';const zipCode=c.cep||e.cep||'';const ie=d.inscricoes_estaduais||c.inscricoes_estaduais||first(d,['inscricao_estadual','ie'])||null;return{cnpj:d.cnpj||c.cnpj||value,companyName:c.razao_social||d.razao_social||'',tradeName:c.nome_fantasia||d.nome_fantasia||'',phone:first(d,['telefone1','telefone_1','telefone','telefone2','telefone_2'])||'',email:first(d,['email','email_principal'])||'',status:c.situacao_cadastral||d.situacao_cadastral||'',address,number,neighborhood,city,state,zipCode,cnae:first(d,['cnae_fiscal','codigo_cnae','subclasse','cnae'])||((c.atividade_principal||{}).subclasse)||null,cnaeDescription:first(d,['cnae_fiscal_descricao','descricao_cnae'])||'',porte:d.porte||c.porte||'',inscricoesEstaduais:ie,source:'CNPJ_WS_PUBLIC'}}
async function companyStatusForLead(leadId){const events=await runtime.repository.listEvents({leadId,type:'COMPANY_STATUS_UPDATED',limit:20});const e=events.find(x=>x.payload?.status);return e?.payload?.status||null}
async function crmRoute({method,path:p,query,body,headers}){if(!authorized(headers))return{status:401,body:{error:'CRM_AUTH_REQUIRED'}};if(!runtime.repository)return{status:503,body:{error:'CRM_DATABASE_NOT_CONFIGURED'}};
if(method==='GET'&&p==='/api/crm/health'){const h=await databaseHealth();return{status:200,body:{status:'ok',database:h.body.database,configured:true}}}
if(method==='GET'&&p==='/api/crm/cnpj'){try{return{status:200,body:{company:await lookupCnpj(query.cnpj)}}}catch(e){const map={CNPJ_INVALIDO:400,CNPJ_NAO_ENCONTRADO:404,CNPJ_RATE_LIMIT:429};return{status:map[e.message]||502,body:{error:e.message}}}}
if(method==='GET'&&p==='/api/crm/leads'){const leads=await runtime.repository.listLeads({limit:Math.min(Number(query.limit||100),200),source:query.source||undefined,status:query.status||undefined});const enriched=[];for(const l of leads){enriched.push({...l,companyStatus:await companyStatusForLead(l.id),assistantScore:scoreLead(l),assistantPriority:priority(scoreLead(l))})}return{status:200,body:{leads:enriched}}}
if(method==='POST'&&p==='/api/crm/leads'){if(!body?.phone)return{status:400,body:{error:'PHONE_REQUIRED'}};try{const lead=await runtime.repository.createLead({...body,phone:String(body.phone).replace(/\D/g,''),source:body.source||'MANUAL'});await runtime.repository.createEvent({lead_id:lead.id,type:'LEAD_CREATED',payload:{source:lead.source,assistantScore:scoreLead(lead)}});if(body.companyStatus)await runtime.repository.createEvent({lead_id:lead.id,type:'COMPANY_STATUS_UPDATED',payload:{status:String(body.companyStatus).toUpperCase()}});return{status:201,body:{lead:{...lead,companyStatus:body.companyStatus||null,assistantScore:scoreLead(lead),assistantPriority:priority(scoreLead(lead))}}}}catch(e){if(e?.code==='23505')return{status:409,body:{error:'LEAD_ALREADY_EXISTS'}};return{status:500,body:{error:'LEAD_CREATE_FAILED'}}}}
const m=p.match(/^\/api\/crm\/leads\/([^/]+)\/messages$/);if(method==='GET'&&m)return{status:200,body:{messages:await runtime.repository.listMessages({leadId:decodeURIComponent(m[1]),limit:200})}};
const a=p.match(/^\/api\/crm\/leads\/([^/]+)\/assistant-summary$/);if(method==='GET'&&a){const lead=await runtime.repository.getLead(decodeURIComponent(a[1]));if(!lead)return{status:404,body:{error:'LEAD_NOT_FOUND'}};return{status:200,body:buildLeadSummary(lead)}}
const ev=p.match(/^\/api\/crm\/leads\/([^/]+)\/events$/);if(method==='GET'&&ev)return{status:200,body:{events:await runtime.repository.listEvents({leadId:decodeURIComponent(ev[1]),limit:200})}};
if(method==='GET'&&p==='/api/crm/appointments'){const events=await runtime.repository.listEvents({type:'APPOINTMENT_CREATED',limit:200});const date=query.date?String(query.date):null;const appointments=events.filter(e=>{const start=e.payload?.startAt;return start&&(!date||String(start).slice(0,10)===date)}).map(e=>({id:e.id,leadId:e.lead_id,startAt:e.payload?.startAt||null,endAt:e.payload?.endAt||null,mode:e.payload?.mode||'PRESENCIAL',address:e.payload?.address||null,city:e.payload?.city||null,state:e.payload?.state||null,confirmed:Boolean(e.payload?.confirmed),createdAt:e.created_at||null}));return{status:200,body:{appointments}}}
if(method==='POST'&&p==='/api/crm/appointments/rank'){const slots=rankAppointmentSlots(Array.isArray(body?.slots)?body.slots:[],body?.constraints||{});return{status:200,body:{slots}}}
if(method==='POST'&&p==='/api/crm/appointments'){if(!body?.leadId||!body?.startAt)return{status:400,body:{error:'LEAD_ID_AND_START_AT_REQUIRED'}};const lead=await runtime.repository.getLead(body.leadId);if(!lead)return{status:404,body:{error:'LEAD_NOT_FOUND'}};const idempotencyKey=String(body.idempotencyKey||`appointment:${lead.id}:${body.startAt}`);const existing=await runtime.repository.listEvents({leadId:lead.id,type:'APPOINTMENT_CREATED',limit:200});const duplicate=existing.find(e=>String(e.idempotency_key||'')===idempotencyKey);if(duplicate)return{status:200,body:{appointment:duplicate,duplicate:true}};const event=await runtime.repository.createEvent({lead_id:lead.id,type:'APPOINTMENT_CREATED',idempotency_key:idempotencyKey,payload:{startAt:body.startAt,endAt:body.endAt||null,mode:body.mode||'PRESENCIAL',address:body.address||lead.address||null,city:body.city||lead.city||null,state:body.state||lead.state||null,confirmed:Boolean(body.confirmed)}});return{status:201,body:{appointment:event,duplicate:false}}}
if(method==='POST'&&p==='/api/crm/routes/plan'){const stops=Array.isArray(body?.stops)?body.stops:[];const plan=buildRoutePlan(stops,{date:body.date,startAt:body.startAt,endAt:body.endAt,origin:body.origin});const event=body?.persist&&body?.leadId?await runtime.repository.createEvent({lead_id:body.leadId,type:'ROUTE_PLANNED',payload:plan}):null;return{status:200,body:{...plan,persisted:Boolean(event),event}}}
if(method==='POST'&&p==='/api/crm/send'){const lead=await runtime.repository.getLead(body.leadId);if(!lead)return{status:404,body:{error:'LEAD_NOT_FOUND'}};if(!body.text)return{status:400,body:{error:'TEXT_REQUIRED'}};const qr=String(lead.source||'').match(/^WHATSAPP_QR_SLOT\_(\d+)$/);if(qr&&qrManager){if(Number(qr[1])!==1)return{status:403,body:{error:'V1_ONLY_ONE_WHATSAPP'}};const r=await qrManager.send(1,{to:lead.phone,text:body.text});await runtime.repository.createMessage({lead_id:lead.id,channel:'WHATSAPP',direction:'OUTBOUND',external_message_id:r?.key?.id||null,text_content:body.text,metadata:{provider:'BAILEYS_QR',slot:1}});return{status:200,body:{sent:true,provider:'BAILEYS_QR'}}}if(!runtime.sender)return{status:503,body:{error:'WHATSAPP_SENDER_NOT_CONFIGURED'}};const r=await runtime.sender.sendText({to:lead.phone,text:body.text});await runtime.repository.createMessage({lead_id:lead.id,channel:'WHATSAPP',direction:'OUTBOUND',external_message_id:r?.messages?.[0]?.id||null,text_content:body.text,metadata:{provider:'META_WHATSAPP'}});return{status:200,body:{sent:true,provider:'META_WHATSAPP'}}}
return{status:404,body:{error:'CRM_ROUTE_NOT_FOUND'}}}
async function whatsappRoute({method,path:p,headers}){if(!authorized(headers))return{status:401,body:{error:'CRM_AUTH_REQUIRED'}};if(!qrManager)return{status:503,body:{error:'QR_MANAGER_NOT_READY'}};if(method==='GET'&&p==='/api/whatsapp/slots')return{status:200,body:{slots:qrManager.list().filter(s=>Number(s.slot)===1)}};const m=p.match(/^\/api\/whatsapp\/slots\/(\d+)\/(connect|disconnect)$/);if(m&&method==='POST'){const slot=Number(m[1]);if(slot!==1)return{status:403,body:{error:'V1_ONLY_ONE_WHATSAPP'}};return{status:200,body:m[2]==='connect'?await qrManager.connect(1):await qrManager.disconnect(1)}}return{status:404,body:{error:'WHATSAPP_ROUTE_NOT_FOUND'}}}
async function routeRequest({method,path,query={},body={},rawBody='',signatureHeader='',headers={}}={}){if(method==='POST'&&path==='/api/auth/login'){try{return{status:200,body:auth.login(body.user,body.password)}}catch(e){return{status:401,body:{error:'INVALID_CREDENTIALS'}}}}if(method==='POST'&&path==='/api/auth/logout'){const v=String(headers.authorization||'');if(v.startsWith('Bearer '))auth.logout(v.slice(7));return{status:200,body:{ok:true}}}if(method==='GET'&&path==='/api/auth/status')return{status:200,body:{configured:auth.configured(),authenticated:authorized(headers)}};if(method==='GET'&&path==='/health')return{status:200,body:healthResponse()};if(method==='GET'&&path==='/health/db')return databaseHealth();if(method==='GET'&&path==='/webhooks/meta')return verifyMetaWebhook(query);if(method==='POST'&&path==='/webhooks/meta'){const config=getConfig();if(!config.metaAppSecret||!verifyMetaSignature(rawBody,signatureHeader,config.metaAppSecret))return{status:401,body:{error:'META_SIGNATURE_INVALID'}};const messages=normalizeMetaWebhook(body);if(!runtime.pipeline)return{status:503,body:{error:'PERSISTENCE_NOT_CONFIGURED'}};if(messages.length)runtime.pipeline(messages).catch(e=>console.error('WEBHOOK_PIPELINE_ERROR',e?.message));return{status:200,body:{received:true,count:messages.length}}}if(method==='GET'&&path==='/'){const f=staticFile('index.html');return f?{status:200,body:f.body,raw:true,contentType:f.contentType}:{status:404,body:{error:'NOT_FOUND'}}}if(method==='GET'&&['/app.js','/styles.css'].includes(path)){const f=staticFile(path.slice(1));return f?{status:200,body:f.body,raw:true,contentType:f.contentType}:{status:404,body:{error:'NOT_FOUND'}}}if(path.startsWith('/api/crm'))return crmRoute({method,path,query,body,headers});if(path.startsWith('/api/whatsapp'))return whatsappRoute({method,path,headers});return{status:404,body:{error:'NOT_FOUND'}}}
module.exports={routeRequest,normalizeMetaWebhook,verifyMetaWebhook,databaseHealth,lookupCnpj};